# -*- coding: utf-8 -*-
"""NLTK Course - Stemming.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e7OEsmk7Uh5K8AMQNA6vl2ufl0_0XRbp

There are different stemmers.

- The Porter Stemmer, if you are working with English, is good enough. PorterStemmer is known for its simplicity and speed.

- LancasterStemmer was developed in 1990 and uses a more aggressive approach than Porter Stemming Algorithm.

- Snowball stemmers that can be used for 13 languages like Dutch, English, French, German, Italian, Portuguese, Romanian, Russian, and so on.
"""

from nltk.stem import PorterStemmer 
from nltk.stem.lancaster import LancasterStemmer 
 
pst = PorterStemmer()  
lst = LancasterStemmer() 
#lst.stem("eating")  
pst.stem("shopping")



sentence="Pythoners are very intelligent and work very pythonly and now they are pythoning their way to success."
pst.stem(sentence)