# -*- coding: utf-8 -*-
"""NLTK Course - Stop Words.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P4TTnHR-SKJW9kXwrbz47Mo-IspKDAYG
"""

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
print(stopwords.words('english'))

from nltk.corpus import stopwords
stoplist = stopwords.words('english') 
text = "This is just a test"
cleanwordlist = [word for word in text.split() if word not in stoplist]
print(cleanwordlist)

stopwords.fileids()