# -*- coding: utf-8 -*-
"""NLTK Course - NLTK Installation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IykAvn_-jl7b-L56e9grG_b_VzFUTZG1
"""

!pip install nltk

import nltk
nltk.download()

nltk.download('gutenberg')
nltk.corpus.gutenberg.fileids()

emma = nltk.corpus.gutenberg.words('austen-emma.txt')

len(emma)

nltk.download('punkt')
nltk.corpus.gutenberg.sents('austen-emma.txt')