# -*- coding: utf-8 -*-
"""NLTK Course - NER Tagging.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-OHEaCsjT9jKfKVrh3GguEbbqF79YDVV

geo = Geographical Entity

org = Organization

per = Person

gpe = Geopolitical Entity

tim = Time indicator

art = Artifact

eve = Event

nat = Natural Phenomenon
"""

import nltk
from nltk import ne_chunk
from nltk.tokenize import word_tokenize

nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

sent = "Mark is studying at Stanford University in California and he started in September 2019"
print(ne_chunk(nltk.pos_tag(word_tokenize(sent)), binary=False))