# -*- coding: utf-8 -*-
"""NLTK Course - POS_tag.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WxOmJRpTMYnkZDSVOXOk-2HpS3qdKfdI
"""

import nltk
from nltk import word_tokenize
nltk.download("punkt")
nltk.download('averaged_perceptron_tagger')

my_string = "I was eating dinner"
my_tokens = word_tokenize(my_string)
tagged = nltk.pos_tag(my_tokens)
print(tagged)